version: '3'
services:
  gateway:
    build: .
    environment:
      - PORT=8080
      - SEARCH_SERVICE_URL=https://search-rtfemypala-as.a.run.app
      - PLATFORM_SERVICE_URL=https://platform-rtfemypala-as.a.run.app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
